services:
  - type: web
    name: plearn-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.9
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: PERENUAL_API_KEY
        sync: false
